CUDA_VISIBLE_DEVICES=0 python sot_glp/train_sot_glp.py \
--clip_name clip_vit_b16 \
--exp_name fgvc_aircraft_shot_16 \
--save_dir ./results \
--dataset_name fgvc_aircraft \
--data_dir data \
--max_epoch 200 \
--accum_batch_size 32 \
--original_batch_size 128 \
--eval_ood False \
--eval_domains False \
--eval_freq 10 \
--checkpointing_segments 0 \
--use_local_features True \
--lr_init 0.01 \
--warmup_epoch 0 \
--num_shots 16 \
--parallel_text_encoder True \
--parallel_vision_encoder True \
--use_global_loss True \
--learn_global_prompt True \
--n_global_prompts 3 \
--use_local_loss True \
--learn_local_proj True \
--learn_local_prompts True \
--n_local_prompts 2 \
--topk 10 10 10 10
