CUDA_VISIBLE_DEVICES=7 python sot_glp/train_sot_glp.py \
    --clip_name clip_vit_b16 \
    --exp_name imagenet_shot_16 \
    --save_dir ./results \
    --dataset_name imagenet \
    --data_dir data \
    --max_epoch 50 \
    --batch_size 256 \
    --eval_ood True \
    --eval_domains False \
    --eval_freq 5 \
    --checkpointing_segments 5 \
    --use_local_features True \
    --lr_init 0.01 \
    --warmup_epoch 0 \
    --num_shots 16 \
    --parallel_text_encoder True \
    --parallel_vision_encoder True \
    --use_global_loss True \
    --learn_global_prompt True \
    --n_global_prompts 3 \
    --use_local_loss True \
    --learn_local_proj True \
    --learn_local_prompts True \
    --n_local_prompts 4 \
    --topk 10 10 10 10
